package com.mycompany.client.resources.images;

import com.google.gwt.resources.client.ClientBundle;
import com.google.gwt.resources.client.DataResource;

/**
 * Auto Generated by mk_images.rb on Fri Nov 30 22:39:12 -0500 2012
 */
public interface MyImages extends ClientBundle


{
	
	
    @Source("a/facebook.png")
    public DataResource facebookIconImageData();

    @Source("a/flickr.png")
    public DataResource flickrIconImageData();

    @Source("a/github.png")
    public DataResource githubIconImageData();

    @Source("a/google.png")
    public DataResource googleIconImageData();

    @Source("a/linkedin.png")
    public DataResource linkedinIconImageData();

    @Source("a/twitter.png")
    public DataResource twitterIconImageData();

    @Source("a/vimeo.png")
    public DataResource vimeoIconImageData();

    @Source("a/wordpress.png")
    public DataResource wordpressIconImageData();

    @Source("a/yahoo.png")
    public DataResource yahooIconImageData();
    
    @Source("a/instagram.png")
    public DataResource instagramIconImageData();
    
    @Source("a/imgur.png")
    public DataResource imgurIconImageData();
    
    @Source("a/live32.png")
    public DataResource liveIconImageData();
    
    @Source("a/tumblr.png")
    public DataResource tumblrIconImageData();
    
    @Source("a/foursquare.png")
    public DataResource foursquareIconImageData();
    
    @Source("a/close.png")
    public DataResource closeIconImageData();
    
    @Source("a/busy.gif")
    public DataResource busyIconImageData();
    
}
